### ISSUE TITLE
Zeebe-simple-monitor fails to start when connecting to a redis cluster

### ISSUE THREAD

**Issue by amitonlentra** [camunda-community-hub/zeebe-simple-monitor#689]
We are trying to start up zeebe-simple-monitor but it fails when trying to connect to a redis cluster. The error in the logs are as below. Note that the application works if redis is running with `cluster-enabled` as false. Redis was installed following this [link](https://medium.com/geekculture/redis-cluster-on-kubernetes-c9839f1c14b6). We verified through redis-cli that the cluster mode is enabled.

Also we are able to see zeebe being able to successfully connect with redis (cluster mode). 
Can someone guide us on resolving this?

Zeebe monitor k8s manifest file

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeebemonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeebemonitor
  template:
    metadata:
      labels:
        app: zeebemonitor
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: k3s
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: k3s
                    operator: In
                    values:
                      - zeebemonitor
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: zeebemonitor
          image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.1
          ports:
          - name: web
            containerPort: 8089
          env:
            - name: ZEEBE_CLIENT_BROKER_GATEWAYADDRESS
              value: "dev-zeebe-gateway:26500"
            - name: ZEEBE_CLIENT_BROKER_SECURITY_PLAINTEXT
              value: "true"
            - name: ZEEBE_CLIENT_WORKER_REDIS_CONNECTION
              value: "redis://redis-cluster:6379"
            - name: ZEEBEIMPORTER
              value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: zeebemonitor

spec:
  selector:
    app: zeebemonitor
  ports:
    - port: 8089
      targetPort: 8089
```

Zeebe monitor start up failure logs
```
___                 __
 _/  _  _ |_   _   (_  .  _   _  |  _   |\/|  _   _  . |_  _   _
/__ (- (- |_) (-   __) | ||| |_) | (-   |  | (_) | ) | |_ (_) |
                             |

================================================================
                                

2024-03-21T11:49:52.803Z  INFO 1 --- [  restartedMain] io.zeebe.monitor.ZeebeSimpleMonitorApp   : Starting ZeebeSimpleMonitorApp using Java 21.0.2 with PID 1 (/app/classes started by root in /)
2024-03-21T11:49:52.807Z DEBUG 1 --- [  restartedMain] io.zeebe.monitor.ZeebeSimpleMonitorApp   : Running with Spring Boot v3.2.3, Spring v6.1.4
2024-03-21T11:49:52.807Z  INFO 1 --- [  restartedMain] io.zeebe.monitor.ZeebeSimpleMonitorApp   : No active profile set, falling back to 1 default profile: "default"
2024-03-21T11:50:02.214Z ERROR 1 --- [  restartedMain] i.c.c.auth.DefaultNoopAuthentication     : Unable to determine authentication. Please check your configuration
2024-03-21T11:50:02.819Z  INFO 1 --- [  restartedMain] i.z.m.zeebe.redis.ZeebeRedisService      : Connecting to Redis redis://redis-cluster, consumer group simple-monitor
2024-03-21T11:50:02.924Z  INFO 1 --- [  restartedMain] i.z.m.zeebe.redis.ZeebeRedisService      : Importing records from Redis...
2024-03-21T11:50:03.518Z  INFO 1 --- [  restartedMain] i.z.r.c.java.RedisConnectionBuilder      : Read from Redis streams 'zeebe:*' with offset '0-0'
2024-03-21T11:50:03.613Z ERROR 1 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zeebeRedisService': Invocation of init method failed
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:222) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.4.jar:6.1.4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.4.jar:6.1.4]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.3.jar:3.2.3]
        at io.zeebe.monitor.ZeebeSimpleMonitorApp.main(ZeebeSimpleMonitorApp.java:55) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) ~[spring-boot-devtools-3.2.3.jar:3.2.3]
Caused by: io.lettuce.core.RedisCommandExecutionException: MOVED 9099 10.42.15.140:6379
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.internal.Exceptions.bubble(Exceptions.java:72) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.internal.Futures.awaitOrCancel(Futures.java:250) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:75) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at jdk.proxy2/jdk.proxy2.$Proxy166.xgroupCreate(Unknown Source) ~[na:na]
        at io.zeebe.redis.connect.java.RedisConnectionBuilder.lambda$build$0(RedisConnectionBuilder.java:240) ~[zeebe-redis-connector-0.9.11.jar:0.9.11]
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
        at io.zeebe.redis.connect.java.RedisConnectionBuilder.build(RedisConnectionBuilder.java:237) ~[zeebe-redis-connector-0.9.11.jar:0.9.11]
        at io.zeebe.monitor.zeebe.redis.RedisImportService.importFrom(RedisImportService.java:34) ~[classes/:na]
        at io.zeebe.monitor.zeebe.redis.ZeebeRedisService.start(ZeebeRedisService.java:45) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219) ~[spring-beans-6.1.4.jar:6.1.4]
        ... 21 common frames omitted
Caused by: io.lettuce.core.RedisCommandExecutionException: MOVED 9099 10.42.15.140:6379
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:745) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:680) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:597) ~[lettuce-core-6.3.1.RELEASE.jar:6.3.1.RELEASE/12e6995]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by amitonlentra** [comment]
@VonDerBeck - Is there a difference in the redis connectivity code between zeebe-simple-monitor and the connector module of redis-exporter given that zeebe works but this fails?

**Comment by VonDerBeck** [comment]
@amitonlentra 
Your trying to connect to a cluster? 
Please set environment parameter `zeebe.client.worker.redis.useClusterClient=true`
And let us know, if this works.

**Comment by amitonlentra** [comment]
sorry for the false alarm. Yes the connectivity worked after enabling this parameter. Thank you very much for the quick response.
